### ISSUE TITLE
Behavior correct?

### ISSUE THREAD

**Issue by o4rz3l** [MarcoIeni/release-plz#1064]
Hi @MarcoIeni, 

I'm indirectly using your "next_version" crate via the "git-cliff" cli tool. I came across the following situation.
I have tested conventional commits with 0.0.1 on and tried to bump via commits. Doing so with fix and none conventional commit increased the patch by one, so far so good. Then I tried a feat and it increased only the patch.
In the following file you write

> If a feature comment, is present and the major number is not 1,
> than the minor is incremented

With the major >1 this is true, but not with major == 0, as the following test shows clearly.

https://github.com/MarcoIeni/release-plz/blob/8baa179206108529a2b594b3ec88ea450df51169/crates/next_version/src/lib.rs#L28

If this is correct (do you have some reference via this is implemented in this way) how should I be able to increment the minor version or even reach 1.0.0 vie conventional commits?

Thanks in advance!

Ref: https://github.com/orhun/git-cliff/issues/343

**Comment by MarcoIeni** [comment]
Hi, this is the intended behavior.
The reason is that imo a bump from 0.0.x to 0.1.x and from 0.x.y to 1.0.0 should be intentional and not automated because the author communicates an higher level of stability to the user.
This is why crates in rust stays at "0.x.y" forever :)

> how should I be able to increment the minor version or even reach 1.0.0 vie conventional commits?

You can't.

If you want this kind of behavior, you can start from 1.0.0, instead of 0.0.1.

This behavior is documented in the [docs](https://docs.rs/next_version/latest/next_version/):
![image](https://github.com/MarcoIeni/release-plz/assets/11428655/a5469f4c-fb4a-4423-ab46-f68b1a19f966)

In #1065 I moved this section up, so that it takes precedence over the rule you copy pasted :)

> do you have some reference via this is implemented in this way

Sorry, I don't have time to look for this, but this behavior is what makes sense for the Rust ecosystem.

Sorry for the inconvenience!
