### ISSUE TITLE
`auto-formatting-enabled` field in configuration

### ISSUE THREAD

**Issue by simonsan** [MarcoIeni/release-plz#1276]
## Motivations

If you are running a lint on a certain format for files in your repository, release-plz PRs will most likely fail in CI. This is annoying, because it involves checking out the branch, format it and push it back to its origin. For example, if you are using something like [dprint](https://dprint.dev/).

- Would you like to implement this feature? n

## Solution

Have a flag in the config file, that people can opt-in/opt-out to auto-formatting. release-plz and its corresponding GH Action would then check for a few known formatter configuration files (e.g. dprint.json) in the root dir and run the formatter. This would need the tools to be made available in the GH Action. So it might make sense to start out with one, as it might be a bit more integration work?

## Alternatives

First I thought the easiest way would be to add a field to the to make formatting configurable via a command to be run. Then run the command given in the field before a new commit is made and pushed to the release branch. Locally this would be way easier, because the person does have to make sure themselves, that the command is working out as it should (e.g. installing formatters beforehand). 
But for a [GH Action](https://github.com/MarcoIeni/release-plz-action), it would be a bit more complicated, which makes me think that it may be easier to implement it in a way, that abstracts over the formatting tools.

## Additional context

tbd?

**Comment by MarcoIeni** [comment]
Hi simonsan 👋 
I think `auto-formatting-enabled` is the wrong level of abstraction for release-plz. I don't want to embed third-party tools in the release-plz action itself.
Instead, what it would be nice to allow, is running ANY github action step after release-plz creates the PR.
So people can format using the dprint github action itself.

To do this, I think it's sufficient to return the release pr branch from release-plz action output. What do you think? This feature is similar to https://github.com/MarcoIeni/release-plz-action/issues/88

At the moment, the release-plz github action doesn't return any output.

One note on your specific issue. I saw the dprint option fails because CHANGELOG.md is not formatted well.
![image](https://github.com/MarcoIeni/release-plz/assets/11428655/5d936a87-1aa8-4bde-b1ca-eca18d6b25dd)

You can either:

- customize the [changelog format](https://release-plz.ieni.dev/docs/changelog-format) to add a new line after the `## header`
- ignore CHANGELOG.md in dprint config

**Comment by MarcoIeni** [comment]
> To do this, I think it's sufficient to return the release pr branch from release-plz action output.

Recorded this in https://github.com/MarcoIeni/release-plz-action/issues/88

Closing this 👍
