### ISSUE TITLE
generated CHANGELOG.md not Markdown compliant

### ISSUE THREAD

**Issue by mbodmer** [MarcoIeni/release-plz#1652]
## Bug description

The generated changelogs are not Markdown compliant. Markdownlint brings up at least:

- MD022 - [Headings should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md022.md)
- MD032 - [Lists should be surrounded by blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md032.md)
- MD024 - [Multiple headings with the same content](https://github.com/DavidAnson/markdownlint/blob/v0.34.0/doc/md024.md)

MD022 and MD032 could be easily fixed in the default template.

MD024 however would still be there, as it is a legitimate case for changelogs.

One possibility to tackle the lint errors would be a .markdownlint.json:

```json
{
    "no-duplicate-heading": {
        "siblings_only": true
    },
    "line-length": {
        "headings": false
    },
    "blanks-around-headings": {
        "lines_below": 0
    },
    "blanks-around-lists": false
}
```

This however will affect the whole project and especially the blanks around headings and lists and also line length are possibly desirable in other files.

There is also a possibility of adding the lint configuration in a comment of the file like so:

```md
<!-- markdownlint-configure-file { "MD022": { "lines_below": 0 }, "MD032": false, "MD024": { "siblings_only": true } } -->
# Changelog
...
```

This however might not be wanted in a PR body, but only in CHANGELOG.md

I think there should be a fix, but I am unsure which way would be best. My personal argumentation might be:

- I wouldn't want a .markdownlint.json which affects the whole project just to calm the linter on CHANGELOG.md files which are generated by a tool
- I wouldn't want to switch of markdownlint in the IDE because of generated CHANGELOG.md
- I wouldn't want any comments in PR bodies which might not be understood by a web rendering engine
- I wouldn't want to change the default template in release-plz.toml when there is otherwise no configuration needed in my project

This leads me to the proposal:

- fix the lines around headings and lists in the default template or add it to the markdownlint comment
- add the markdownlint comment as shown above as the first line when generating the CHANGELOG.md files, and not the PR

### git-cliff

Git cliff has also tackled this already, maybe @orhun would jump in with an idea. see:

- https://github.com/orhun/git-cliff/issues/60
- https://github.com/orhun/git-cliff/pull/61

**Comment by mbodmer** [comment]
There is one thing. I actually would be happy to only have the changelog added to the PR bodies and no files generated. If this is possible in the settings I wouldn't be bothered with markdownlint warnings, but I didn't spot this feature yet :-)

**Comment by orhun** [comment]
> There is also a possibility of adding the lint configuration in a comment of the file like so:

FWIW we configure the Markdownlint settings [Ratatui](https://github.com/ratatui/ratatui/blob/main/cliff.toml#L15) in a similar way:

```toml
[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
<!-- ignore lint rules that are often triggered by content generated from commits / git-cliff -->
<!-- markdownlint-disable line-length no-bare-urls ul-style emphasis-style -->
"""
```

---

Additionally, I'm thinking of adding a built-in style checker in the future: <https://github.com/orhun/git-cliff/issues/678>

Although this might be quite straightforward to use with the `postprocessors`:

```toml
# regex for preprocessing the commit messages
postprocessors = [
  { pattern = '.*', replace_command = 'markdownlint --fix --stdin' },
]
```

Oh wait, did I say straightforward? It turns out it does not support using `--fix` with `--stdin` for some unspoken reason, ugh:

```shell
  -f, --fix                                  fix basic errors (does not work with STDIN)
  -s, --stdin                                read from STDIN (does not work with files)
```

Reported here: https://github.com/igorshubovych/markdownlint-cli/issues/497

**Comment by MarcoIeni** [comment]
The default release-plz changelog should follow https://keepachangelog.com/en/1.1.0/

Unfortunately I just found out that's not the case because release-plz generates changelog without adding the new line between `###` and the changes.

E.g.

correct:
```
### Added

- v1.1 Brazilian Portuguese translation.
```

vs release-plz:
```
### Added
- v1.1 Brazilian Portuguese translation.
```

PR welcome to fix this 👍


Also, you can completely customize release-plz changelog how you like: https://release-plz.ieni.dev/docs/config#the-changelog-section

> There is one thing. I actually would be happy to only have the changelog added to the PR bodies and no files generated. If this is possible in the settings I wouldn't be bothered with markdownlint warnings, but I didn't spot this feature yet :-)

From what I remember disabling https://release-plz.ieni.dev/docs/config#the-changelog_update-field-package-section also doesn't show the changelog in the pr body but I'm not sure. you can test it and let me know 👍

If you want this feature, please open a new issue so we can discuss it 👍

**Comment by MarcoIeni** [comment]
closed by https://github.com/MarcoIeni/release-plz/pull/1653
