### ISSUE TITLE
Release-plz race condition on merge queues

### ISSUE THREAD

**Issue by MarcoIeni** [MarcoIeni/release-plz#1805]
## Bug description

[This](https://github.com/MarcoIeni/release-plz/blob/f22270c7d28e0e2129569f7d4ef73628216b0d5e/website/docs/usage/release.md#L122) section of the doc is wrong is wrong because a merge queue will always rebase before merging. This means that release-plz will also release any changes merged after the release-pr was updated the last time.
This means that those changes will not be available in the CHANGELOG and won't be analyzed by semver-checks.

Temporary fix: don't merge other changes while you are merging the release pr.

## Possible solutions

- release-plz should check if the last commit on main is the last one that he created the release pr. How do we save "the last commit that release-plz analyzed"? Maybe on pr label

## actions

- [ ] update the docs asap

**Comment by danking** [comment]
FWIW, we ran into this issue without merge queues. If you use squash-merge and you merge too fast, you can get a race.

We're going to try to fix this by guarding the `command: release` GitHub action with `if: startsWith(github.event.head_commit.message, 'chore: release')`.

**Comment by MarcoIeni** [comment]
For that there's the [release_always](https://release-plz.ieni.dev/docs/config#the-release_always-field) config field. Isn't it what you want to achieve?

Also, I don't understand how your condition fixed the race condition 🤔
The release commit will still contain the other commit.

**Comment by danking** [comment]
Hey @MarcoIeni,

Apologies! I misunderstand what issue #1805 is about. If I now understand correctly, #1805 is concerned about this timeline:
1. Commit A merges into main.
2. Before the release PR can be updated to include a changelog item for Commit A, the release PR is squash-merged into main.
3. The release PR GitHub action will create a release including Commit A's code but not including a changelog.

Do I understand that correctly?

---

We're actually concerned about the opposite ordering, heh! What happens when a commit merges after the release commit but before the release commit's GitHub Action runs to completion. We do not use merge queues.

We observed this timeline:

1. The release-plz release pull request was squash-merged into main as Commit 1. [link](https://github.com/spiraldb/vortex/commit/453fa610f2279fd9e4c53431caabfa048ac61079)
5. The release-plz action runs on Commit 1. [link](https://github.com/spiraldb/vortex/actions/runs/11630848959/job/32390669039)
6. While (2) runs, another PR is squash-merged into main as Commit 2. [link](https://github.com/spiraldb/vortex/commit/f83a0933063e9d12f20938c0f0e9a94e4c43f652)
7. A second release-plz action starts running on Commit 2. [link](https://github.com/spiraldb/vortex/actions/runs/11630955081/job/32390985113)
8. These two actions race with one another to publish crates.
9. The action for Commit 2 rapidly notices that most crates are already published.
10. The action for Commit 1 and the action for Commit 2 are racing to publish some crate. If Commit 2 wins the race then the published crate will contain Commit 2 which is not in CHANGELOG.md!

Perhaps I'm mistaken about point (7), but my understanding from the [docs on release-plz release](https://release-plz.ieni.dev/docs/usage/release) is that, because we use squash-merge, the release-plz action always releases the commit which triggered the action. It does not checkout the most recent commit which update the CHANGELOG.md. Am I mistaken?
> If you merge with the [squash and merge](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github#squashing-your-merge-commits) strategy, the git checkout won't happen because when you merge the PR to the main branch, GitHub creates a new commit, so release-plz won't find the commit of the PR and will release the latest commit of the main branch.

---

I want to be able to pick some commit, Commit A, and be guaranteed that either that commit is published to crates.io or no commit is published to crates.io. I'd rather have a gap in version numbers than have some later commit become the released version.

The condition is meant to restrict the `release-plz release` GitHub Action to only release PRs. Obviously a malicious developer could create a PR with the title "chore: release" but we rely on reviews and trust to prevent that.

**Comment by MarcoIeni** [comment]
> Do I understand that correctly?

yes.

> Am I mistaken?

You are right!

I think the solution to your issue is setting `release_always = false`. Did you evaluate [release_always](https://release-plz.ieni.dev/docs/config#the-release_always-field)?

**Comment by danking** [comment]
Ah, I did not find that flag! I think that suffices for our purposes. Thanks!

I suppose this is a config file variable which is why it’s not disabled by default in GitHub Actions? Disabled seems to me like the preferred behavior if you’re in GitHub if the config file has no particular setting.

**Comment by MarcoIeni** [comment]
So you are saying that `release_always = false` is a better default?
I think it's more intuitive for beginners to have `release_always = true` because they can do manual changes without using a release pr. Plus, people can use `release-plz release` without `release-pr`.

- [ ] But I think this race condition should be documented better so that people can set `release_always = false` if they are in a busy repo 👍

**Comment by MarcoIeni** [comment]
I discovered that this is not true. Example:

<img width="1412" alt="image" src="https://github.com/user-attachments/assets/098e00e9-6184-41a2-82bd-cf3bb7b6870b">


So this issue is not valid 👍 There's no race condition when using merge queues.

I will raise a PR to document the squash and merge problem
