### ISSUE TITLE
Support for `workspace-inheritance`

### ISSUE THREAD

**Issue by nahsi** [MarcoIeni/release-plz#279]
[`workspace-inheritance`](https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace) will be released in Rust on [September 22, 2022](https://forge.rust-lang.org/#current-release-versions). Any plans to support it?

- Would you like to implement this feature? [y/n] n

**Comment by MarcoIeni** [comment]
I didn't know about this. Thanks.
Yes, we should definitely support it.
PRs are welcome of course.
But once it becomes stable, I will try to play around with the feature and see if I can some time to implement support for it :)

**Comment by MarcoIeni** [comment]
https://github.com/killercup/cargo-edit supports this, so we could see what they've done there :)

**Comment by MarcoIeni** [comment]
Hey! 👋  I was looking at this issue tonight. However, it seems like nothing needs to be changed to support workspace inheritance.
For example, I tried adding a bunch of workspace dependencies in [this](https://github.com/MarcoIeni/release-plz/pull/333) branch, and then I run `release-plz update` and it works as expected.

Am I missing something? Can you provide an example where release-plz doesn't handle workspace-inheritance well?
Otherwise I think we can just close this issue 🤔

**Comment by MarcoIeni** [comment]
I'm closing this issue. If you find problems related to `workspace-inheritance`, please write a comment here 👍
