### ISSUE TITLE
Changelog Missing From Release

### ISSUE THREAD

**Issue by XAMPPRocky** [MarcoIeni/release-plz#642]
The first release of octocrab using [release-plz](https://github.com/XAMPPRocky/octocrab/releases/tag/v0.20.0-alpha.1) doesn't include any of the changes, looking at the release-plz used in this repo, I don't see anything obvious as to why yours works and mine doesn't.

**Comment by XAMPPRocky** [comment]
Thank you for your help, I've updated the changelog, does it look right to you?

**Comment by XAMPPRocky** [comment]
Hmm, this PR seems wrong, it just appends the changelog again, also shouldn't open a PR for changes that don't affect anything. Is there a way I can configure it to only open a release PR on a set schedule, for example "every six weeks on Thursday"?

https://github.com/XAMPPRocky/octocrab/pull/322

**Comment by MarcoIeni** [comment]
> I've updated the changelog, does it look right to you?

Unfortunately at the moment, the release-plz mechanism of recognizing the changelog header is very stupid. It needs to be exactly [this](https://github.com/MarcoIeni/release-plz/blob/6306e4f6acce4ae02e30b71956ec9248aa87ef65/crates/release_plz_core/src/changelog.rs#L13).

Instead you have the line "All Octocrab releases are supported by the community and through [GitHub Sponsors](https://github.com/sponsors/XAMPPRocky).".

I opened https://github.com/MarcoIeni/release-plz/issues/643 to address this issue.

---

> also shouldn't open a PR for changes that don't affect anything.

Define "anything" 😛
At the moment release-plz detects changes from all files under the same directory of the Cargo.toml (which for single-crate projects like octocrab means every file 😅).
However, The CHANGELOG file is part of what you release on crates.io (you can verify by running `cargo package --list`, so in my opinion release-plz should raise a PR if the changelog file changes.
This morning I have added [this](https://github.com/MarcoIeni/release-plz/issues/410#issuecomment-1492853172) comment to an issue, so that we can honor the `cargo package --list`.
So that you can add files you are not interested in (like ci files under the `.github` directory) in the `exclude` array of Cargo.toml:
```toml
[package]
# ...
exclude = ["/ci", "images/", ".*"]
```

Release-plz in the future will raise PRs only for files present in the `cargo package --list`. Could this solve your issue? What do you think about this approach?

---

>  Is there a way I can configure it to only open a release PR on a set schedule, for example "every six weeks on Thursday"?

Sure, I documented it [here](https://github.com/MarcoIeni/release-plz/pull/644/files).

---

## Tip: how to test release-plz locally

If you want to test the content of the release-plz pr without committing in your `main` branch, you can run `release-plz update` locally in your project and then run `git diff` :)

---

Btw, release-plz is my main side-project, but as you can see from the opened issue, there's a lot to do!
If you want to see a certain feature implemented sooner rather than later, I'm very happy to accept external contributions :)

**Comment by MarcoIeni** [comment]
I implemented https://github.com/MarcoIeni/release-plz/issues/643, so you should be able to keep your current changelog.
The next time you run release-plz, it should update the changelog correctly 👍

**Comment by MarcoIeni** [comment]
The latest PR on octocrab looks much better!
![image](https://user-images.githubusercontent.com/11428655/230192172-317c7b3f-789a-431c-a8cf-513fb103da9d.png)
I'm closing this issue to keep the issue tracker cleaner, but feel free to continue the conversation either here or in another issue 👍

**Comment by XAMPPRocky** [comment]
> Define "anything"

That's fair, I think I'm mostly just annoyed by the "Update CHANGELOG.md" commits which seem superfluous to add to the changeling itself.

**Comment by MarcoIeni** [comment]
yes, but normally you only update the changelog in the release-pr, which is not included in the changelog of the next release 👍
