### ISSUE TITLE
Implement `release-plz set-version` command

### ISSUE THREAD

**Issue by XAMPPRocky** [MarcoIeni/release-plz#704]
## Motivations

After using `release-plz` for awhile now, I was ready to move Octocrab to normal releases, and I realised I didn't know how to tell it "Move to regular releases". My initial instinct / hope was that I could just remove the suffix in the `Cargo.toml`, and the PR would adjust itself, but it doesn't seem like that happened, instead the `0.20.0` was released with an incomplete changelog. 

- Would you like to implement this feature? [n] (no time unfortunately)

## Solution

I'd like some kind of workflow where I can manually say "this is release now". I think ideally it could be a command I can put in the PR itself like `@release-plz pre-release` or `@release-plz prod-release` or something similar and have the open PR update itself into incrementing the next production release version. 

## Alternatives

I'm sure there's a lot of ways it can be done, like having it react when someone removes the suffix, or updating a config file, but ideally for me the solution would require no additional commits, and can be performed entirely on github.com

**Comment by MarcoIeni** [comment]
> My initial instinct / hope was that I could just remove the suffix in the Cargo.toml, and the PR would adjust itself, but it doesn't seem like that happened, instead the 0.20.0 was released with an incomplete changelog.

Yes, release-plz releases anything it finds on the main branch.

At the moment release-plz doesn't have the ability to "switch" from pre-release to prod-releases, so unfortunately you need to do this manually, by adjusting Cargo.toml and the changelog. You can edit the PR itself, and then merge it.

It's an interesting feature to have, and `actions` triggered by PR comments sound cool! 

> for me the solution would require no additional commits, and can be performed entirely on github.com

💯 

Before switching to the actual implementation we need to define the exact behavior. These are some of the questions I have:

- what happens if I have a workspace with many crates and I run `@release-plz pre-release` or `@release-plz prod-release`?
  - All the crates change versions?
  - Just the ones modified in the PR?
  - Should you be able to specify the single crates in this action?
- Let's say you have a crate at version 1.2.3. What happens when you switch to pre-release? Does it go to `1.2.4-alpha.1`? Why not `1.2.4-beta.1`? How do we pick one? What's the best default? Should the prefix be in the config file?

**Comment by XAMPPRocky** [comment]
I think the simplest version that would work initially would just be a `set-version` command that lets me override whatever the proposed version is with a new version.

**Comment by MarcoIeni** [comment]
You are right! What about workspaces?

`@release-plz set-version crate-a@1.0.0`?

We can use the `cargo add` syntax.

**Comment by XAMPPRocky** [comment]
That makes sense to me, for my part I usually try to have all crates in a workspace share the version number, so I'd assume without specifying the crate it would set it for all crates in the workspace.

**Comment by MarcoIeni** [comment]
yes 👍 In this case, should release-plz edit only the version of the packages that changed in the PR? Or all the packages in the workspace?

**Comment by XAMPPRocky** [comment]
I think intuitively the default should only update what's in the PR, and then you could have a `--workspace` flag to update everything.

**Comment by MarcoIeni** [comment]
After thinking about https://github.com/MarcoIeni/release-plz/issues/770#issuecomment-1550290553 I realized that
- [ ] the commands given in the github comments of the action should be re-applied everytime the PR is updated

so making the outcome of the PR dependent of the content of the PR might result being messy.
So let's start with ignoring what file changes in the PR. I.e. the output of the command should be the same if run on `main` or in a branch.

**Comment by MarcoIeni** [comment]
I implemented this command. It works locally! https://release-plz.ieni.dev/docs/usage/set-version
Closing this because I'm tracking the remaining work in https://github.com/MarcoIeni/release-plz/issues/1554 and https://github.com/MarcoIeni/release-plz/issues/1559
