### ISSUE TITLE
Only include the first line of changes in the changelog

### ISSUE THREAD

**Issue by XAMPPRocky** [MarcoIeni/release-plz#727]
Below is the [proposed changelog for octocrab 0.21.0](https://github.com/XAMPPRocky/octocrab/pull/337), as you can see there's a lot of extraneous information such as the `Co-Authored-By` header in the changelog because it's including the full commit message rather than just the first line, it would be nice if by default it did not do that.

<img width="903" alt="Screenshot 2023-04-24 at 09 52 25" src="https://user-images.githubusercontent.com/4464295/233933584-080b2081-2adb-49f0-8584-7f684e45de4b.png">

**Comment by MarcoIeni** [comment]
Oops, I think this is due to a recent change, I will fix this and release a new version between today and tomorrow 👍

It should show only the commit title, right?

**Comment by XAMPPRocky** [comment]
> It should show only the commit title, right?

I think so, at least that should be the default in my opinion.


Thank you for working on this great project! 🙏

**Comment by MarcoIeni** [comment]
This is fixed in main, but I encountered [this](https://github.com/MarcoIeni/release-plz/issues/731) problem when releasing, so the github action is not fixed yet.
In the meantime, please manually edit the changelog of the release-pr before merging.

> Thank you for working on this great project! 🙏

Thanks! I used octocrab in many occasions, so I'm happy I can give back :)

**Comment by MarcoIeni** [comment]
This is fixed in the action version v0.5.2 👍
