### ISSUE TITLE
Breaking change in patch release

### ISSUE THREAD

**Issue by XAMPPRocky** [MarcoIeni/release-plz#767]
## Bug description

This is probably more of a bug in the semver checks, I figure to start the issue here since people using release-plz might run into it.

In this release a breaking change (changing the type of a public member) wasn't caught as a breaking change and so the release is a patch release, but if I did release it as a patch I could potentially break downstream users.

https://github.com/XAMPPRocky/octocrab/pull/356

**Comment by MarcoIeni** [comment]
Hi 👋 
I'm sorry about your issue. I'm aware that cargo-semver-checks doesn't catch every semver violation.
I documented this [here](https://github.com/MarcoIeni/release-plz/blob/a0325da45e4645b6e69252a2050a5ace092b440b/docs/src/usage/update.md#L13).

cargo-semver-checks mentions the issue you reported in their [readme](https://github.com/obi1kenobi/cargo-semver-checks#will-cargo-semver-checks-catch-every-semver-violation).

I'm inclined to close this issue because as you said there's not much we can do here, apart from contributing to cargo-semver-checks :)

Before closing this, do you think we should add more docs about this? Maybe a bigger warning? Or an invite to double-check possible semver breaking changes?

**Comment by XAMPPRocky** [comment]
Thank you for your response, I think this mostly creates a stronger need for the `set-version` command we talked before in #704 since I now again have another case where need to change the version in the pr.

**Comment by MarcoIeni** [comment]
Yeah, you are right! Unfortunately it's not a quick change, because we would need to introduce a new command, read pr comments, etc.

I will get to that eventually, but for the time being, we need to edit release prs by hand 😅

**Comment by XAMPPRocky** [comment]
Clarify editing them to me. Is it safe for me to just edit the version in the PR, or do I need to do something else?

**Comment by MarcoIeni** [comment]
> Is it safe for me to just edit the version in the PR

Yes! You can edit the PR as you wish and then merge it!

You can change the version and the changelog, for example 👍

**Comment by MarcoIeni** [comment]
I'm closing this issue because I documented your questions in https://github.com/MarcoIeni/release-plz/pull/769

Thanks for the feedback, I really appreciate it. It helps me write better docs 🙏 

If you have other questions feel free to re-open this or create new issues 👍
