### ISSUE TITLE
Edited PR is closed rather than updated

### ISSUE THREAD

**Issue by XAMPPRocky** [MarcoIeni/release-plz#770]
Hello again, I followed your advice to edit the PR to the correct version, however after new changes were merged which required `release-plz` to update the PR it instead closed the PR and opened a new one. It would be more intuitive if the PR was updated rather than closed, as I'd prefer to be able to update it once and forget rather than needing to remember to edit and release.

https://github.com/XAMPPRocky/octocrab/pull/356
https://github.com/XAMPPRocky/octocrab/pull/362

**Comment by MarcoIeni** [comment]
Hi! I'm sorry you have to open all these issues. I wish release-plz were better and more intuitive. 😅

## When release-plz closes a PR?

Release-plz closes the old PR when it contains a commit done by a non-bot account. In https://github.com/XAMPPRocky/octocrab/pull/356 release-plz detected your commits, and so it closed that PR and opened the new one.
![image](https://github.com/MarcoIeni/release-plz/assets/11428655/f765b1ce-3b49-401e-ab44-a3ac6f50cebb)

Release-plz also closes the release PR when it cannot update it (for example, the force-push fails). (This not the case of this issue).

## When release-plz updates a pr?

Release-plz updates a PR when it wasn't updated by a [non-bot](https://github.com/MarcoIeni/release-plz/blob/11e3cd08386094ebca3a488c40b4af9e6a7e4ba9/crates/release_plz_core/src/release_pr.rs#L112) user.
The update mechanism is simple: overwrite everything and force-push. 💥 

Reasoning: changes done by bots are not valuable, so we can overwrite them.

## Why release-plz closes a PR?

Release-plz closes a PR instead of updating it (by force-pushing), to prevent loosing precious commits.
If this mechanism weren't in place, release-plz would force-push the new changes, overriding maintainers commits. 
Instead, thanks to the closed PR, maintainers can at least cherry-pick their changes in the old PRs and apply them to the new one.

## Problem with the current approach

> It would be more intuitive if the PR was updated rather than closed, as I'd prefer to be able to update it once and forget rather than needing to remember to edit and release.

I agree that updating it once and forget would be nice.
My approach until now has been different: only look at the release pr when I want to release, do all the changes and merge.

- [ ] For sure, there is a gap in the docs I need to document.

## Feature request: smart update

What you are proposing is: instead of updating the PR by overwriting everything, release-plz should compare the new changes with the old ones and merge the two.

This involves:
- merging the old and the new changelog.
- merging the old and the new version.

We need to decide which criteria to use with these merges. I'm not sure it's possible to find good enough rules. I'll give it a try:

### Edit changelog

For the changelog, keep the entries that are not duplicated. In this case:
- what if people moved the entries from one section of the changelog to another (e.g. from Other to Added)? We would have two duplicate entries.
- what if people edit an entry? Again, we would have duplicate entries. Not ideal.

Editing the changelog also implies parsing it properly, which at the moment, we don't do.
The changelog format is not standard (it can be customized with git cliff). Does git-cliff support parsing the changelog? I don't remember now.

### Edit version

For the version, we can decide to keep the highest one. E.g. release-plz detects that the next version should be 0.2.1, but the old release pr contains 0.3.0 -> release-plz keeps 0.3.0.

This doesn't work in case of `git force-push` where somebody rewrites the git-history to remove the breaking commit. Release-plz will always suggest the version (which would be a breaking one).

### Conclusion

As you can see, implementing this "smart update" is very difficult, and it can add a lot of complexity in the release-plz codebase.
What do you think?

**Comment by XAMPPRocky** [comment]
> Hi! I'm sorry you have to open all these issues. I wish release-plz were better and more intuitive. 😅

Don't apologise, real-world user feedback and iterating is how it can become better and more intuitive 🙂 This still a lot better than previous solutions in the space.

> What you are proposing is: instead of updating the PR by overwriting everything, release-plz should compare the new changes with the old ones and merge the two.

To be clear, I'm not proposing that. The thing I want as a user is a clear workflow (in the abstract user experience sense, not GitHub workflow) that lets me update the version in the PR, and have that change stick after it updates. For example; I'm totally fine with it not being safe to edit the PR, if there's a workflow for me to update the PR such as the comment we mentioned before.

> I agree that updating it once and forget would be nice. My approach until now has been different: only look at the release pr when I want to release, do all the changes and merge.

Yeah, I have a different intention, once I feel like I the automated release PR is good enough, I intend to add a second GitHub workflow that merges these PRs on a regular schedule, completely automating release management out of my hands. So I won't be the "person" merging this PR, which is why for me, if I have to edit the PR, I'd want it to stick and remain the same PR, rather than opening a new one.

My opinion on the "smart update" stuff, if you implemented that I would want it be that it's append-only, I'd rather have the changelog look ugly than lose my changes, because I can always tidy it up after the fact. But I think my preferred solution is still having a GitHub comment based interface and requiring all the intended changes to go through that, because it's less complex and more consistent.

**Comment by MarcoIeni** [comment]
Let's go with option 2. I captured this requirement in https://github.com/MarcoIeni/release-plz/issues/704#issuecomment-1606140039
