### ISSUE TITLE
Release PRs are not opened when using `publish = false`

### ISSUE THREAD

**Issue by alcaprar** [MarcoIeni/release-plz#777]
## Bug description

When using the `publish = false` config (i.e. a binary), the `release-pr` command only works the first time. All the subsequent calls do not generate a release PR.

From the logs I can see:
```
INFO  using release-plz config file release-plz.toml
INFO  downloading packages from cargo registry
WARN  Package `release-plz-replicate-bug@*.*.*` not found
INFO  release-plz-replicate-bug: next version is 0.1.0
INFO  the repository is already up-to-date
```

## To Reproduce

I was able to reproduce it in this repo, I also gave you writer access: https://github.com/alcaprar/release-plz-replicate-bug.

1. Init the `release-pr` command: https://github.com/alcaprar/release-plz-replicate-bug/commit/dcc1f1a12d17bb93ee05767f6a23b509d324bf3a
2. First automated release: https://github.com/alcaprar/release-plz-replicate-bug/commit/a1d5eac8d14970ee59c03f5b904655b6fd41afbe
3. New commit that did not trigger a new PR: https://github.com/alcaprar/release-plz-replicate-bug/commit/f7600285ff3f84d2c0afac14b213e49739a255eb

## Environment

- release-plz version: `MarcoIeni/release-plz/release-plz-v0.3.8/linux-x64`

![immagine](https://github.com/MarcoIeni/release-plz/assets/11180418/1260a7ee-a245-4ca6-81bf-370db894955a)

**Comment by MarcoIeni** [comment]
> When using the publish = false config (i.e. a binary)

Why do you say "i.e. a binary"? You can still publish binaries to crates.io so that people can run `cargo install`.

> All the subsequent calls do not generate a release PR.

This is because there's no update to do.
If you run `release-plz update` locally you also see that there are no changes to do.

## Why there are no changes?

- There's no version published on crates.io, so the next version is still 0.1.0, which is already what you have in Cargo.toml
- the changelog already contains the 0.1.0 release

## Expected behavior

Since you expected the release PR to be created, what do you expect to see in the PR diff?

Release-plz doesn't work if you don't publish your crate to a cargo registry (for example, crates.io). The `publish = false` config is there because you might want to run `cargo publish` manually.

**Comment by alcaprar** [comment]
> Why do you say "i.e. a binary"? You can still publish binaries to crates.io so that people can run cargo install.
Yes, true. In my case, I did not want to publish to crates.io but just upload the binary into the GitHub release.

> Release-plz doesn't work if you don't publish your crate to a cargo registry (for example, crates.io).
Ok, so I misunderstood something. I thought it would use GitHub tags as well (that I actually did not even create in the linked repo, I forgot to add the `release` step) if no crate was found in crates.io. It does not seem to be a real bug anymore then :)

**Comment by MarcoIeni** [comment]
> I did not want to publish to crates.io but just upload the binary into the GitHub release.

I see, this is a legit use case, that I also considered implementing [here](https://github.com/MarcoIeni/release-plz/issues/590#issuecomment-1519170017).
However, I discarded it because it adds complexity to release-plz. The reason why I created release-plz was to better intact with crates.io.

For your use case you might want to look at [release-please](https://github.com/googleapis/release-please), because that's what it does: it only creates the git tag without publishing to crates.io :)
