### ISSUE TITLE
Publishing fails for crates that depend on other crates in a workspace when the version is shared from workspace

### ISSUE THREAD

**Issue by frol** [MarcoIeni/release-plz#803]
## Bug description

Here is the failing job: https://github.com/near/borsh-rs/actions/runs/5159201221/jobs/9294017741

borsh-derive depends on borsh-derive-internal. The latter has been published just fine, but the former cannot be published and I guess it is related to the version of borsh-derive-internal which cannot be properly extracted as it is [`version.workspace = true`](https://github.com/near/borsh-rs/blob/7ee182a7a5b325203308ca70484a5e5fc30db2a6/borsh-derive-internal/Cargo.toml#L3).

- Would you like to work on a fix? n (I don't have the capacity right now)

## To Reproduce

Re-run the publishing job.

## Expected behavior

It should release borsh-derive and borsh crates just fine.

**Comment by MarcoIeni** [comment]
I think the issue is that you need to specify the version of your local dependencies.
For example [here](https://github.com/near/borsh-rs/blob/7ee182a7a5b325203308ca70484a5e5fc30db2a6/borsh-derive/Cargo.toml#L19).
This is required by `cargo publish` itself. If you are able to publish with `cargo publish`, but release-plz fails, let me know.

I do the same in [release-plz](https://github.com/MarcoIeni/release-plz/blob/3cdf9895269062d800a9fa8c6b9ad66b137026f8/crates/release_plz/Cargo.toml#L15).

**Comment by frol** [comment]
@MarcoIeni Thanks! Specifying the version explicitly did the trick
