### ISSUE TITLE
Stopped working after the first merge

### ISSUE THREAD

**Issue by elbaro** [MarcoIeni/release-plz#840]
## Bug description

After I merge the first PR by release-plz, it stopped creating new PRs.
https://github.com/elbaro/downtown/pull/18

## To Reproduce

1. Creates a PR
2. Merge
3. Github action runs
4. No PR is created

## Expected behavior

Create a new PR

## Environment

- release-plz version:  MarcoIeni/release-plz-action@v0.5

## Additional context

- The main branch is protected.
- There is an old branch left by release-plz.
- I didn't publish the crate to the registry.
- The Github action log had no useful info.

**Comment by MarcoIeni** [comment]
This is the expected behavior.

From [logs](https://github.com/elbaro/downtown/actions/runs/5385426616/jobs/9774425646):
<img width="1533" alt="Screenshot 2023-06-27 at 08 50 37" src="https://github.com/MarcoIeni/release-plz/assets/11428655/c7a4912f-3cbb-4e81-9a22-3ad102d4a595">
You local Cargo.toml has version 0.1.1, while crates.io has version 0.1.0.

Which version should release-plz update to? None, right?

Release-plz is waiting for you to publish your current version.

Since [here](https://github.com/elbaro/downtown/blob/319772367a5148000ed16f7c9a68610f4978672d/.github/workflows/release-plz.yml#L26) you specified `release-pr`, release-plz won't publish the version for you.

I hope I was clear, let me know if you still have doubts.
Can I improve the docs in some way to make this more explicit?

**Comment by elbaro** [comment]
I see. Actually I wanted release-pr to work locally and only depend on the local Cargo.toml version.

Can I change this issue to a feature request that adds a config to make release-pr read the version from the local Cargo.toml?

**Comment by MarcoIeni** [comment]
No, sorry. Release-plz needs a cargo registry to do his job (public or private).
For private registries there's an issue open but I will look into it.

I explained why is complied to support projects that are not published to a cargo registry in https://github.com/MarcoIeni/release-plz/issues/590

**Comment by elbaro** [comment]
> #590 

understood, thanks!
