### ISSUE TITLE
Make it possible to only publish crates to the registry and nothing more

### ISSUE THREAD

**Issue by Veetaha** [MarcoIeni/release-plz#951]
## Motivations

I have a complex release process where git tagging, version bumps and github release creation is handled by myself. All that is left for me is to run `cargo publish`. Unfortunatelly, `cargo` doesn't make it simple to publish all crates in the workspace automatically, I have to publish them all one by one manually.

## Solution

I'd like to have an option in `release-plz` to only do the `cargo publish`. It must not require a git token. It should only call `cargo publish` and that's it.

## Alternatives

I'm considering to use `cargo release` CLI to achive this

**Comment by MarcoIeni** [comment]
Hi 👋 
Imo if you like the "release pr" mechanism, you should stick with release-plz. Otherwise, if you only want to `cargo publish` you can also consider as alternatives:
- [`cargo-workspace publish`](https://github.com/pksunkara/cargo-workspaces#publish).
- `cargo release` with some args should work too, as you said.

Release-plz can already disable git releases with the config option [`git_release_enable`](https://release-plz.ieni.dev/docs/config#the-git_release_enable-field).
It cannot disable git tags yet, but it's a simple change: we should add a `git_tag_enable` option similar to `git_release_enable`.
Then propagate this option [here](https://github.com/MarcoIeni/release-plz/blob/a88c026880d98da1a4884f7e73a937304a90d1f3/crates/release_plz_core/src/command/release.rs#L368) and add an `if input.is_git_tag_enabled` as we do for the releases below on line 373.

Regarding the git token, at the moment, it's mandatory, so we should make it optional if git releases (and tags?) are disabled. In practice, you can put a random string until we don't make it optional, because it will never be used.

Now, some questions for you:
- was I clear enough or you have more questions?
- do you still want to use release-plz for your use case? If yes, are you interested in contributing by adding the `git_tag_enable` request?

**Comment by Veetaha** [comment]
Hi, everything is clear. I've been considering to use `release-plz` for my release setup. I see it as a good tool for managing the releases of general purpose libraries. Unfortunatelly, it doesn't suit entirely for my use case, but I still wanted to use it for publishing the crates if it would be as simple as adding a github action to the CI template, but there is the problem that `release-plz` wants to set the git tags.

You are right, `release-plz` doesn't fit for me. I solved my problem with `cargo release` for now.

But here is the flow that I use for releasing that may be useful for you.
- I have a separate CI job that uses a `workflow_dispatch` event (meaning you can invoke it manually via github UI) accepts optionally the version that to assign to the crates. I make sure all crates have the same version, and the way release-plz maintains separate versions for different crates doesn't suit me. It also doesn't allow overriding the version to assign to crates.
- The workflow then does the thing similar to `release pr`, but it doesn't create a PR, but pushes the commits directly to master. It first creates a release version e.g. `1.2.0` and puts a tag on it, and then sets a "dev" version for the next release cycle e.g. `1.2.1-dev`. If you don't specify any version, it will parse the latest version from the CHANGELOG.md file. It also cuts the portion of the changelog for the latest version and sets it as the Github release description.
- The other workflow is subscribed to `tag` events and it is responsible for creating a github release, building and uploading the binary artifacts and publishing the rust crates. At this point no modifications to the sources files are needed.

**Comment by MarcoIeni** [comment]
Thank you for the detailed answer. Your use case is very useful!

>  there is the problem that release-plz wants to set the git tags.

Fixed this in #968 👍 

> the way release-plz maintains separate versions for different crates doesn't suit me

Release-plz supports using a workspace version. See [this](https://github.com/XAMPPRocky/rasn/pull/143/files) example.

> It also doesn't allow overriding the version to assign to crates.

You are right, you need to do it manually. We need to implement the features described in https://github.com/MarcoIeni/release-plz/issues/704 

I'm happy you found the workflow that works for you. Best of luck with marker, it's a project I always wanted :)
